Add Netlify button
tidbcloud/vercel-fortune500-demo pull request #4
Opened 2023-02-07 06:48 UTC by shiyuhang0

- Add Netlify button to deploy to Netlify.
- Delete hello.js

2023-02-07 07:05 UTC, shiyuhang0 commented
@zoubingwu PTAL 
and i don't known how to pass the check

2023-02-07 07:34 UTC, zoubingwu requested changes

2023-02-07 07:34 UTC, zoubingwu commented on package.json
> +    "netlify-build": "npm run build"
Why it'll have to add another duplicated script? Why not just use `npm run build`?

2023-02-08 05:48 UTC, zoubingwu approved these changes

2023-02-08 05:48 UTC, merged